server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3000/videosharingplatformDB?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    initialize: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true